#!/usr/bin/python3
#
# geracao de nomes

import random


def lista_cursos(quantidade):
    cursos = [
        {"campus": "Lagoa do Sino", "modalidade": "Presencial",
         "nome": "Bacharelado em Administracao", "sigla": "Adm-LS"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Bacharelado em Administracao", "sigla": "Adm-So"},
        {"campus": "Araras", "modalidade": "Presencial",
         "nome": "Bacharelado em Agroecologia", "sigla": "Ae-Ar"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Bacharelado em Agronomia", "sigla": "Ag/A-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Biblioteconomia e Ciencia da Informacao",
         "sigla": "BCI"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Biblioteconomia e Ciencia da Informacao - Informacao e Inovacao Tecnologica",
         "sigla": "BCIT"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Biblioteconomia e Ciencia da Informacao - Informacao Empresarial",
         "sigla": "BCIE"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Biblioteconomia e Ciencia da Informacao - Informacao, Ciencia e Sociedade",
         "sigla": "BCIS"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Biblioteconomia e Ciencia da Informacao - Informacao, Cultura e Discurso",
         "sigla": "BCID"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Biotecnologia", "sigla": "Biotec"},
        {"campus": "Araras", "modalidade": "Presencial",
         "nome": "Bacharelado em Biotecnologia", "sigla": "Biotec-Ar"},
        {"campus": "Araras", "modalidade": "Presencial",
         "nome": "Bacharelado em Biotecnologia - Agricola",
         "sigla": "Biotec-ArAg"},
        {"campus": "Araras", "modalidade": "Presencial",
         "nome": "Bacharelado em Biotecnologia - Ambiental",
         "sigla": "Biotec-ArAm"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencia da Computacao", "sigla": "CC"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencia da Computacao", "sigla": "CC-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencias Biologicas", "sigla": "CB"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Ciencias Biologicas", "sigla": "CBL"},
        {"campus": "Araras", "modalidade": "Presencial",
         "nome": "Licenciatura em Ciencias Biologicas", "sigla": "CBL-Ar"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencias Biologicas", "sigla": "CB-So"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Licenciatura em Ciencias Biologicas", "sigla": "CBLN-So"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Licenciatura em Ciencias Biologicas", "sigla": "CBL-So"},
        {"campus": "Lagoa do Sino", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencias Biologicas", "sigla": "CBio-LS"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencias Economicas", "sigla": "CEc-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencias Sociais", "sigla": "CSo"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencias Sociais - Antropologia",
         "sigla": "CSoA"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencias Sociais - Politica", "sigla": "CSoP"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Ciencias Sociais - Sociologia",
         "sigla": "CSoS"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Educacao Especial", "sigla": "EEspL"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Educacao Fisica", "sigla": "EF"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Educacao Fisica", "sigla": "EFL"},
        {"campus": "Sao Carlos", "modalidade": "A distancia",
         "nome": "Licenciatura em Educacao Musical", "sigla": "EMusL/D"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Enfermagem", "sigla": "Enf"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Enfermagem - Formacao Pedagogica Complementar",
         "sigla": "EnfP"},
        {"campus": "Araras", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Agronomica", "sigla": "EAg-Ar"},
        {"campus": "Lagoa do Sino", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Agronomica", "sigla": "EAg-LS"},
        {"campus": "Lagoa do Sino", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Ambiental", "sigla": "EAm-LS"},
        {"campus": "Sao Carlos", "modalidade": "A distancia",
         "nome": "Bacharelado em Engenharia Ambiental", "sigla": "EAm/D"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Civil", "sigla": "ECiv"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Civil - Engenharia Urbana",
         "sigla": "ECivU"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Civil - Sistemas Construtivos",
         "sigla": "ECivC"},
        {"campus": "Lagoa do Sino", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia de Alimentos", "sigla": "EAl-LS"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia de Computacao", "sigla": "EC"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia de Materiais", "sigla": "EMa"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia de Materiais - Materiais Ceramicos",
         "sigla": "EMaC"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia de Materiais - Materiais Metalicos",
         "sigla": "EMaM"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia de Materiais - Materiais Polimericos",
         "sigla": "EMaP"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia de Producao", "sigla": "EP"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia de Producao", "sigla": "EP-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Eletrica", "sigla": "EE"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Fisica", "sigla": "EFi"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Florestal", "sigla": "EFl-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Mecanica", "sigla": "EMec"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Engenharia Quimica", "sigla": "EQ"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Estatistica", "sigla": "Es"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Estatistica - Analise de Riscos e Financas",
         "sigla": "EsR"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Estatistica - Estatisticas Sociais",
         "sigla": "EsE"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Estatistica - Industria", "sigla": "EsI"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Estatistica - Qualidade e Confiabilidade",
         "sigla": "EsQ"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Estatistica - Saude e Meio Ambiente",
         "sigla": "EsS"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Estatistica - Servicos Publicos",
         "sigla": "EsP"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura/Bacharelado em Fisica", "sigla": "F"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Fisica", "sigla": "FB"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Fisica", "sigla": "FL"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Fisica", "sigla": "FLN"},
        {"campus": "Araras", "modalidade": "Presencial",
         "nome": "Licenciatura em Fisica", "sigla": "FL-Ar"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Licenciatura em Fisica", "sigla": "FL-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura/Bacharelado em Filosofia", "sigla": "Fil"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Filosofia", "sigla": "FilB"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Filosofia", "sigla": "FilL"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Fisioterapia", "sigla": "Fisio"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Licenciatura em Geografia", "sigla": "GeoL-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Gerontologia", "sigla": "Gero"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Gestao e Analise Ambiental", "sigla": "GAAm"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Imagem e Som", "sigla": "IS"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Letras", "sigla": "LL"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Letras - Espanhol", "sigla": "LLE"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Letras - Ingles", "sigla": "LLI"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Linguistica", "sigla": "Ling"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura/Bacharelado em Matematica", "sigla": "M"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Matematica", "sigla": "MB"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Matematica", "sigla": "ML"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura/Bacharelado em Matematica", "sigla": "MN"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Matematica", "sigla": "MNB"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Matematica", "sigla": "MNL"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Licenciatura em Matematica", "sigla": "ML-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Medicina", "sigla": "Med"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Musica", "sigla": "MusL"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Pedagogia", "sigla": "PedL"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Pedagogia", "sigla": "PedLN"},
        {"campus": "Sao Carlos", "modalidade": "A distancia",
         "nome": "Licenciatura em Pedagogia", "sigla": "PedL/D"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Licenciatura em Pedagogia", "sigla": "PedL-So"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Pedagogia da Terra", "sigla": "PedTL/A"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Psicologia", "sigla": "Psi"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Quimica", "sigla": "Q"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Quimica - Quimica Tecnologica", "sigla": "QT"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Licenciatura em Quimica", "sigla": "QL"},
        {"campus": "Araras", "modalidade": "Presencial",
         "nome": "Licenciatura em Quimica", "sigla": "QL-Ar"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Licenciatura em Quimica", "sigla": "QL-So"},
        {"campus": "Sao Carlos", "modalidade": "A distancia",
         "nome": "Bacharelado em Sistemas de Informacao", "sigla": "SI/D"},
        {"campus": "Sao Carlos", "modalidade": "A distancia",
         "nome": "Tecnologo em Superior de Tecnologia em Producao Sucroalcooleira",
         "sigla": "TPSa/D"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Terapia Ocupacional", "sigla": "TO"},
        {"campus": "Sao Carlos", "modalidade": "Presencial",
         "nome": "Bacharelado em Traducao e Interpretacao em Lingua Brasileira de Sinais-Libras/Lingua Portuguesa",
         "sigla": "TILSP"},
        {"campus": "Sorocaba", "modalidade": "Presencial",
         "nome": "Bacharelado em Turismo", "sigla": "Tur-So"}
    ]
    return random.sample(cursos, quantidade)


def lista_nomes(quantidade):
    prenomes_masculinos = [
        "Aarao",
        "Abel",
        "Abelardo",
        "Abiliano",
        "Abilio",
        "Abner",
        "Abraao",
        "Abrao",
        "Acacio",
        "Acelino",
        "Adalgiso",
        "Adamantino",
        "Adamo",
        "Adao",
        "Adelino",
        "Adelio",
        "Ademar",
        "Ademario",
        "Ademir",
        "Adolfo",
        "Adonis",
        "Adriano",
        "Adrio",
        "Aecio",
        "Afanasio",
        "Afonsino",
        "Afonso",
        "Afranio",
        "Agamemnon",
        "Agamenon",
        "Agato",
        "Ageu",
        "Agnelo",
        "Alan",
        "Alano",
        "Albertino",
        "Alberto",
        "Albino",
        "Albo",
        "Aldofrido",
        "Alefrido",
        "Aleixo",
        "Alessandrino",
        "Alessandro",
        "Alexandre",
        "Alexandrino",
        "Alexandro",
        "Alfonsino",
        "Alfonso",
        "Alfredino",
        "Alfredo",
        "Alfrido",
        "Alicio",
        "Alino",
        "Almino",
        "Almo",
        "Aloisio",
        "Alonsino",
        "Alonso",
        "Altair",
        "Altamiro",
        "Aluisio",
        "Alvaro",
        "Alvino",
        "Alvo",
        "Amadino",
        "Amado",
        "Amador",
        "Amandino",
        "Amando",
        "Amarildo",
        "Amarino",
        "Amaro",
        "Amelio",
        "Americano",
        "Americo",
        "Amilcar",
        "Amoroso",
        "Amos",
        "Anacleto",
        "Analio",
        "Anderson",
        "Andre",
        "Andrelino",
        "Andresso",
        "Angelico",
        "Angelino",
        "Angelo",
        "Anibal",
        "Anilando",
        "Anilino",
        "Anilio",
        "Anito",
        "Antao",
        "Antoniano",
        "Antonieto",
        "Antonino",
        "Antonio",
        "Anunciado",
        "Aparecido",
        "Aparicio",
        "Apolinario",
        "Apolo",
        "Apolonio",
        "Aquiles",
        "Aquilino",
        "Arcangelo",
        "Ares",
        "Ariadno",
        "Ariano",
        "Aricio",
        "Arielo",
        "Ario",
        "Ariosto",
        "Arlindo",
        "Armandino",
        "Armando",
        "Armenio",
        "Armindo",
        "Arnaldo",
        "Arnoldo",
        "Arsenio",
        "Artur",
        "Ascendino",
        "Ascendo",
        "Ascenso",
        "Asclepio",
        "Astrogildo",
        "Atanasio",
        "Atila",
        "Atiliano",
        "Atilio",
        "Augustino",
        "Augusto",
        "Aureliano",
        "Aurelio",
        "Austregesilo",
        "Auxiliador",
        "Avelino",
        "Barbaro",
        "Bartolomeu",
        "Basiliano",
        "Basilio",
        "Batistino",
        "Belarmino",
        "Benedito",
        "Benigno",
        "Benjamim",
        "Bento",
        "Beremundo",
        "Bermudo",
        "Bernadino",
        "Bernado",
        "Bernardino",
        "Bernardo",
        "Bianco",
        "Brasileiro",
        "Brasiliano",
        "Brasilio",
        "Brendo",
        "Breno",
        "Brigido",
        "Bruno",
        "Caim",
        "Caio",
        "Calvino",
        "Calvo",
        "Camelio",
        "Camilo",
        "Candido",
        "Caninio",
        "Cantidiano",
        "Cantidio",
        "Caricio",
        "Carino",
        "Carlindo",
        "Carlo",
        "Carlos",
        "Carloto",
        "Carmelito",
        "Carmelo",
        "Carolino",
        "Carolo",
        "Catarino",
        "Caue",
        "Ceciliano",
        "Cecilio",
        "Celino",
        "Celio",
        "Celito",
        "Celso",
        "Cesar",
        "Cesariano",
        "Cesarino",
        "Cesario",
        "Charles",
        "Cicero",
        "Cintio",
        "Cipriano",
        "Ciprio",
        "Cipro",
        "Ciriaco",
        "Ciro",
        "Claro",
        "Claudiano",
        "Claudio",
        "Cleber",
        "Clemencio",
        "Clementino",
        "Cleuso",
        "Clodovico",
        "Clodovil",
        "Clovis",
        "Colombino",
        "Colombo",
        "Conrado",
        "Constancio",
        "Constantino",
        "Corvino",
        "Cosme",
        "Cosmo",
        "Creso",
        "Creuso",
        "Cristiano",
        "Cristino",
        "Cristo",
        "Cristovao",
        "Cunegundes",
        "Custodio",
        "Dalilo",
        "Dalvino",
        "Dalvo",
        "Damiao",
        "Daniel",
        "Danilo",
        "Danubio",
        "Dariano",
        "Dario",
        "Davi",
        "David",
        "Deboro",
        "Demerval",
        "Demeter",
        "Demetriano",
        "Demetrio",
        "Demetro",
        "Diago",
        "Diamantino",
        "Diego",
        "Dilmo",
        "Dino",
        "Diogo",
        "Dionisio",
        "Divino",
        "Divo",
        "Domenico",
        "Domingo",
        "Domingos",
        "Donatelo",
        "Donato",
        "Doriano",
        "Dorio",
        "Doro",
        "Doroteu",
        "Douglas",
        "Durval",
        "Durvalino",
        "Ednalvo",
        "Edno",
        "Eduardino",
        "Eduardo",
        "Edvaldino",
        "Edvaldo",
        "Elbo",
        "Eliano",
        "Elias",
        "Elisangelo",
        "Eliseu",
        "Elisiano",
        "Elisio",
        "Eliso",
        "Elzo",
        "Emerenciano",
        "Emerencio",
        "Emerito",
        "Emiliano",
        "Emilio",
        "Eneias",
        "Engraciano",
        "Engracio",
        "Enzo",
        "Epaminondas",
        "Epifanio",
        "Erasmo",
        "Ernestino",
        "Ernesto",
        "Eros",
        "Escolastico",
        "Esculapio",
        "Esmeraldino",
        "Esmeraldo",
        "Esperanco",
        "Estanislau",
        "Estefanio",
        "Estelo",
        "Estevao",
        "Eudoxio",
        "Eufemio",
        "Eufrasino",
        "Eufrasio",
        "Eugeniano",
        "Eugenio",
        "Eulalio",
        "Euniciano",
        "Eunicio",
        "Eusebio",
        "Eustaquio",
        "Eutimio",
        "Evandro",
        "Evangelico",
        "Evangelino",
        "Evangelo",
        "Evaristo",
        "Everaldino",
        "Everaldo",
        "Evo",
        "Expedito",
        "Ezequiel",
        "Fabiano",
        "Fabio",
        "Fabiolo",
        "Fabriciano",
        "Fabricio",
        "Fagundo",
        "Fatimo",
        "Faustiniano",
        "Faustino",
        "Fausto",
        "Feliciano",
        "Felicio",
        "Felix",
        "Ferdinando",
        "Fernandino",
        "Fernando",
        "Fernao",
        "Filipe",
        "Filipino",
        "Filipo",
        "Filomeno",
        "Firmino",
        "Firmo",
        "Flaviano",
        "Flavino",
        "Flavio",
        "Flavo",
        "Florencio",
        "Florentino",
        "Floriano",
        "Florindo",
        "Florisvaldo",
        "Francelino",
        "Francelo",
        "Francielo",
        "Francisco",
        "Fulgencio",
        "Fulviano",
        "Fulvio",
        "Fulvo",
        "Gabriel",
        "Gabrio",
        "Gaio",
        "Galeno",
        "Gardenio",
        "Gaspar",
        "Gasparino",
        "Gaudiano",
        "Gaudio",
        "Genaro",
        "Generoso",
        "Gentil",
        "Geraldino",
        "Geraldo",
        "Germanico",
        "Germanio",
        "Germano",
        "Gilbertino",
        "Gilberto",
        "Giovane",
        "Glafiro",
        "Glendo",
        "Glicerino",
        "Glicerio",
        "Glorio",
        "Godofredo",
        "Goncalo",
        "Goncalvo",
        "Graciano",
        "Graciel",
        "Graciliano",
        "Gracilio",
        "Gracindo",
        "Gracioso",
        "Graco",
        "Graziel",
        "Gregoriano",
        "Gregorio",
        "Guilherme",
        "Guilhermino",
        "Guilhermo",
        "Gustavino",
        "Gustavo",
        "Hamilton",
        "Haroldo",
        "Hector",
        "Heitor",
        "Helenito",
        "Heleno",
        "Helio",
        "Heliodoro",
        "Heliogabalo",
        "Hendrigo",
        "Henrico",
        "Henrique",
        "Henriqueto",
        "Henry",
        "Heracles",
        "Heraclio",
        "Heraclito",
        "Herculano",
        "Hercules",
        "Hermano",
        "Hermes",
        "Hernando",
        "Herodes",
        "Herodiano",
        "Herodio",
        "Hilario",
        "Himeneu",
        "Honestino",
        "Honesto",
        "Honorato",
        "Honorino",
        "Honorio",
        "Horaciano",
        "Horacio",
        "Hugo",
        "Humberto",
        "Iago",
        "Ibraim",
        "Iluminato",
        "Imaculado",
        "Inaciano",
        "Inacio",
        "Inesito",
        "Inocencio",
        "Iolando",
        "Iracemo",
        "Isaias",
        "Isaque",
        "Israel",
        "Italiano",
        "Italio",
        "Italo",
        "Itamar",
        "Ivanildo",
        "Ivano",
        "Ivo",
        "Jacintino",
        "Jacinto",
        "Jaco",
        "Jacomo",
        "Jader",
        "Jaime",
        "Jair",
        "Jairo",
        "Jamil",
        "Janaino",
        "Jandiro",
        "Janino",
        "Jano",
        "Januario",
        "Jeferson",
        "Jeremias",
        "Jessico",
        "Jesuino",
        "Jesus",
        "Joanino",
        "Joao",
        "Joaquim",
        "Jonas",
        "Jonatas",
        "Jorge",
        "Jose",
        "Josefino",
        "Josefo",
        "Josue",
        "Jove",
        "Joviniano",
        "Jovino",
        "Jucaro",
        "Judas",
        "Juliano",
        "Julieto",
        "Julino",
        "Julio",
        "Juniano",
        "Junino",
        "Junio",
        "Jupiter",
        "Juremo",
        "Justiniano",
        "Justino",
        "Justo",
        "Juvenal",
        "Juvencio",
        "Juvenilio",
        "Juventino",
        "Lafaiete",
        "Laudelino",
        "Laudelo",
        "Laudo",
        "Laurencio",
        "Laurentino",
        "Laurito",
        "Lauro",
        "Lavinio",
        "Lazaro",
        "Leandrino",
        "Leandro",
        "Ledico",
        "Leonardino",
        "Leonardo",
        "Leoncio",
        "Leonel",
        "Leonino",
        "Leopoldino",
        "Leopoldo",
        "Lepido",
        "Leticiano",
        "Leticio",
        "Liberalino",
        "Liberato",
        "Libero",
        "Libertario",
        "Libertino",
        "Liberto",
        "Licinio",
        "Liliano",
        "Lilio",
        "Lindalvo",
        "Lindo",
        "Lindolfo",
        "Lirio",
        "Lisandrino",
        "Lisandro",
        "Liviano",
        "Livino",
        "Livio",
        "Lourenco",
        "Lourival",
        "Lucelio",
        "Luciano",
        "Lucifer",
        "Luciliano",
        "Lucilio",
        "Lucilo",
        "Lucio",
        "Ludovico",
        "Luigi",
        "Luis",
        "Lupercio",
        "Luzio",
        "Madaleno",
        "Mafaldo",
        "Magno",
        "Magnolio",
        "Maicon",
        "Mairo",
        "Maiso",
        "Malaquias",
        "Malvino",
        "Malvo",
        "Manuel",
        "Manuelino",
        "Manuelito",
        "Marcel",
        "Marcelino",
        "Marcelo",
        "Marciano",
        "Marciliano",
        "Marcilio",
        "Marcio",
        "Marco",
        "Marcos",
        "Margarido",
        "Marialvo",
        "Mariano",
        "Marildo",
        "Marileno",
        "Marilio",
        "Marino",
        "Mario",
        "Mariso",
        "Maristelo",
        "Martim",
        "Martinho",
        "Martiniano",
        "Martino",
        "Mateus",
        "Matusalem",
        "Maximiliano",
        "Maximilio",
        "Maximo",
        "Melanino",
        "Melanio",
        "Mendo",
        "Mentor",
        "Messias",
        "Micael",
        "Michel",
        "Michelo",
        "Miguel",
        "Miguelino",
        "Mileno",
        "Milton",
        "Miquelangelo",
        "Miquelino",
        "Mirando",
        "Misael",
        "Modestino",
        "Modesto",
        "Moises",
        "Monico",
        "Morgano",
        "Muciano",
        "Mucio",
        "Murilo",
        "Narciso",
        "Natalicio",
        "Natalino",
        "Natalio",
        "Natan",
        "Naum",
        "Nazareno",
        "Nicolas",
        "Nicolau",
        "Nilo",
        "Nilzo",
        "Niveo",
        "Noel",
        "Noelio",
        "Noemio",
        "Normo",
        "Novaciano",
        "Novacio",
        "Novato",
        "Nubio",
        "Numeriano",
        "Numerio",
        "Obadias",
        "Ofelio",
        "Olavo",
        "Olimpiano",
        "Olimpio",
        "Olimpo",
        "Olivio",
        "Olivo",
        "Omar",
        "Onesimo",
        "Orlandino",
        "Orlando",
        "Oseias",
        "Osmar",
        "Osmarino",
        "Osvaldino",
        "Osvaldo",
        "Otaviano",
        "Otavio",
        "Pablo",
        "Paio",
        "Palomino",
        "Palomo",
        "Pamelo",
        "Pancracio",
        "Paolo",
        "Pascalino",
        "Pascoalino",
        "Patricio",
        "Paulino",
        "Paulo",
        "Pedrino",
        "Pedro",
        "Pelagio",
        "Pelaio",
        "Peregrino",
        "Pericles",
        "Perlo",
        "Perolo",
        "Perpetuo",
        "Perseu",
        "Perseverando",
        "Persiano",
        "Persio",
        "Persival",
        "Pietro",
        "Pitagoras",
        "Placidino",
        "Placido",
        "Plinio",
        "Postumio",
        "Postumo",
        "Pretextato",
        "Prisciano",
        "Prisciliano",
        "Priscilo",
        "Prisco",
        "Proteu",
        "Prudenciano",
        "Prudencio",
        "Prudente",
        "Publiano",
        "Publio",
        "Querubim",
        "Quintiliano",
        "Quintilio",
        "Quintino",
        "Quinto",
        "Quiterio",
        "Raimundo",
        "Ramao",
        "Ramiro",
        "Regiano",
        "Reginaldo",
        "Regino",
        "Regio",
        "Regis",
        "Reinaldo",
        "Renan",
        "Renato",
        "Ricardino",
        "Ricardo",
        "Rito",
        "Rodolfo",
        "Rodrigo",
        "Rolando",
        "Romano",
        "Romao",
        "Romario",
        "Ronaldo",
        "Rosalindo",
        "Rosalino",
        "Rosalio",
        "Rosalvo",
        "Rosamundo",
        "Rosangelo",
        "Rosano",
        "Rosario",
        "Rosauro",
        "Rosendo",
        "Rosino",
        "Roso",
        "Sabatino",
        "Sabato",
        "Sabelio",
        "Sabrino",
        "Salustiano",
        "Salustio",
        "Salvador",
        "Salviano",
        "Salvino",
        "Salvio",
        "Salvo",
        "Samanto",
        "Samaritano",
        "Samaro",
        "Samuel",
        "Sancho",
        "Sandrino",
        "Sandro",
        "Santiago",
        "Santino",
        "Santo",
        "Sarito",
        "Saro",
        "Satiro",
        "Saturnino",
        "Saturno",
        "Saul",
        "Saulino",
        "Saulo",
        "Saviano",
        "Savio",
        "Sebastiao",
        "Sempronio",
        "Serafim",
        "Sereno",
        "Sergei",
        "Sergiano",
        "Sergio",
        "Serguei",
        "Severiano",
        "Severino",
        "Severo",
        "Silas",
        "Silvano",
        "Silverino",
        "Silverio",
        "Silvestre",
        "Silvestrino",
        "Silviano",
        "Silvino",
        "Silvio",
        "Simao",
        "Simaro",
        "Simeao",
        "Sinfronio",
        "Sisto",
        "Solano",
        "Susano",
        "Suzano",
        "Tales",
        "Talio",
        "Talito",
        "Tatiano",
        "Telo",
        "Teobaldo",
        "Teodoro",
        "Teofrasto",
        "Tiago",
        "Tomas",
        "Tomasio",
        "Tome",
        "Tranquilino",
        "Tranquilo",
        "Tuliano",
        "Tulio",
        "Ubaldino",
        "Ubaldo",
        "Ubirajara",
        "Ulisses",
        "Ulpiano",
        "Ulpio",
        "Uranio",
        "Urano",
        "Ursulino",
        "Ursulo",
        "Valdir",
        "Valdo",
        "Valenciano",
        "Valencio",
        "Valentim",
        "Valentiniano",
        "Valentino",
        "Valeriano",
        "Valerio",
        "Valesco",
        "Valquirio",
        "Valter",
        "Vando",
        "Vanesso",
        "Vanio",
        "Vanuso",
        "Vasco",
        "Venancio",
        "Venceslau",
        "Venerando",
        "Venino",
        "Veridiano",
        "Veridio",
        "Verissimo",
        "Vermudo",
        "Vero",
        "Veronico",
        "Vespasiano",
        "Vespasio",
        "Vicencio",
        "Vicente",
        "Vicentino",
        "Vinicius",
        "Virtuoso",
        "Vitor",
        "Vitoriano",
        "Vitorio",
        "Xandi",
        "Xisto",
        "Yago",
        "Yan",
        "Yuri",
        "Zacarias",
        "Zairo",
        "Zelio",
        "Zenaido",
        "Zulmiro"
    ]
    prenomes_femininos = [
        "Abelarda",
        "Abigail",
        "Abilia",
        "Abiliana",
        "Acacia",
        "Acelina",
        "Adalgisa",
        "Adama",
        "Adamantina",
        "Adelia",
        "Adelina",
        "Ademaria",
        "Adolfa",
        "Adria",
        "Adriana",
        "Adriane",
        "Aecia",
        "Afanasia",
        "Afonsa",
        "Afonsina",
        "Afrania",
        "Africana",
        "Africano",
        "Afrodite",
        "Agata",
        "Agnela",
        "Agnes",
        "Alana",
        "Alane",
        "Alba",
        "Alberta",
        "Albertina",
        "Albina",
        "Aldofrida",
        "Alefrida",
        "Aleixa",
        "Alessandra",
        "Alessandrina",
        "Alexandra",
        "Alexandrina",
        "Alfonsa",
        "Alfonsina",
        "Alfreda",
        "Alfredina",
        "Alfrida",
        "Alice",
        "Alicia",
        "Alina",
        "Aline",
        "Alma",
        "Almina",
        "Aloisia",
        "Alonsa",
        "Alonsina",
        "Altamira",
        "Aluisia",
        "Alva",
        "Alvara",
        "Alvina",
        "Amada",
        "Amadina",
        "Amadora",
        "Amanda",
        "Amandina",
        "Amara",
        "Amarilda",
        "Amarina",
        "Amelia",
        "America",
        "Americana",
        "Amorosa",
        "Ana",
        "Anacleta",
        "Analia",
        "Ananda",
        "Andreia",
        "Andrelina",
        "Andressa",
        "Ane",
        "Angela",
        "Angelica",
        "Angelina",
        "Anilanda",
        "Anilia",
        "Anilina",
        "Anita",
        "Ano",
        "Antonia",
        "Antoniana",
        "Antonieta",
        "Antonina",
        "Anunciada",
        "Aparecida",
        "Aparicia",
        "Apola",
        "Apolinaria",
        "Apolonia",
        "Aquilina",
        "Arcangela",
        "Aria",
        "Ariadna",
        "Ariadne",
        "Ariana",
        "Ariane",
        "Aricia",
        "Ariel",
        "Ariela",
        "Ariele",
        "Ariene",
        "Ariosta",
        "Arlinda",
        "Armanda",
        "Armandina",
        "Armenia",
        "Arminda",
        "Arnalda",
        "Arnolda",
        "Arsenia",
        "Ascenda",
        "Ascendina",
        "Ascensa",
        "Asclepia",
        "Astride",
        "Astrogilda",
        "Atanasia",
        "Atilia",
        "Atiliana",
        "Augusta",
        "Augustina",
        "Aurelia",
        "Aureliana",
        "Austregesila",
        "Auxiliadora",
        "Avelina",
        "Barbara",
        "Basilia",
        "Basiliana",
        "Batista",
        "Batistina",
        "Beatrice",
        "Beatriz",
        "Belarmina",
        "Benedita",
        "Benigna",
        "Benjamina",
        "Benta",
        "Beremunda",
        "Bermuda",
        "Bernada",
        "Bernadete",
        "Bernadina",
        "Bernarda",
        "Bernardete",
        "Bernardina",
        "Bianca",
        "Brasileira",
        "Brasilia",
        "Brasiliana",
        "Brena",
        "Brenda",
        "Brigida",
        "Bruna",
        "Caia",
        "Calva",
        "Calvina",
        "Camelia",
        "Camila",
        "Camile",
        "Candida",
        "Caninia",
        "Cantidia",
        "Cantidiana",
        "Caricia",
        "Caridade",
        "Carina",
        "Carine",
        "Carla",
        "Carlinda",
        "Carlota",
        "Carmela",
        "Carmelita",
        "Carola",
        "Carolina",
        "Caroline",
        "Catarina",
        "Caua",
        "Cauana",
        "Cauane",
        "Cecilia",
        "Ceciliana",
        "Celia",
        "Celina",
        "Celita",
        "Celsa",
        "Cesaria",
        "Cesariana",
        "Cesarina",
        "Charlene",
        "Charlote",
        "Cicera",
        "Cila",
        "Cintia",
        "Cipra",
        "Cipria",
        "Cipriana",
        "Cira",
        "Ciriaca",
        "Clara",
        "Clarice",
        "Claudia",
        "Claudiana",
        "Cleide",
        "Clemencia",
        "Clemente",
        "Clementina",
        "Cleusa",
        "Clio",
        "Clodovica",
        "Clotilde",
        "Colomba",
        "Colombina",
        "Conrada",
        "Constancia",
        "Constante",
        "Constantina",
        "Corvina",
        "Cosma",
        "Creusa",
        "Crista",
        "Cristiana",
        "Cristiane",
        "Cristina",
        "Cristine",
        "Custodia",
        "Dalila",
        "Dalva",
        "Dalvina",
        "Damiana",
        "Daniela",
        "Daniele",
        "Danila",
        "Danubia",
        "Daria",
        "Dariana",
        "Dariane",
        "Daude",
        "Debora",
        "Deise",
        "Demetra",
        "Demetria",
        "Demetriana",
        "Denise",
        "Devanil",
        "Diaga",
        "Diamantina",
        "Diega",
        "Dilma",
        "Dina",
        "Dioga",
        "Dionisia",
        "Diva",
        "Divina",
        "Domenica",
        "Dominga",
        "Domingas",
        "Donata",
        "Donatela",
        "Dora",
        "Doria",
        "Doriana",
        "Doris",
        "Doroteia",
        "Doroti",
        "Durvalina",
        "Edir",
        "Edna",
        "Ednalva",
        "Eduarda",
        "Eduardina",
        "Eduviges",
        "Edvalda",
        "Edvaldina",
        "Edviges",
        "Elaine",
        "Elba",
        "Electra",
        "Eletra",
        "Eliana",
        "Eliane",
        "Elisa",
        "Elisangela",
        "Elise",
        "Elisia",
        "Elisiana",
        "Eloa",
        "Elza",
        "Emerencia",
        "Emerenciana",
        "Emerita",
        "Emilia",
        "Emiliana",
        "Engracia",
        "Engraciana",
        "Enza",
        "Epifania",
        "Erasma",
        "Ernesta",
        "Ernestina",
        "Escolastica",
        "Esculapia",
        "Esdras",
        "Esmeralda",
        "Esmeraldina",
        "Esperanca",
        "Estefania",
        "Estela",
        "Ester",
        "Eudoxia",
        "Eufemia",
        "Eufrasia",
        "Eufrasina",
        "Eugenia",
        "Eugeniana",
        "Eulalia",
        "Eunice",
        "Eunicia",
        "Euniciana",
        "Euridice",
        "Eusebia",
        "Eustaquia",
        "Eutimia",
        "Eva",
        "Evandra",
        "Evangela",
        "Evangelica",
        "Evangelina",
        "Evangelista",
        "Evarista",
        "Everalda",
        "Everaldina",
        "Expedita",
        "Ezequiela",
        "Fabia",
        "Fabiana",
        "Fabiane",
        "Fabiola",
        "Fabricia",
        "Fabriciana",
        "Fagunda",
        "Fatima",
        "Fausta",
        "Faustina",
        "Faustiniana",
        "Felicia",
        "Feliciana",
        "Felicidade",
        "Ferdinanda",
        "Fernanda",
        "Fernandina",
        "Filemom",
        "Filipa",
        "Filipina",
        "Filomena",
        "Firma",
        "Firmina",
        "Flava",
        "Flavia",
        "Flaviana",
        "Flavina",
        "Flor",
        "Flora",
        "Florencia",
        "Florentina",
        "Floriana",
        "Florinda",
        "Florisvalda",
        "Floro",
        "Francela",
        "Francelina",
        "Franciela",
        "Franciele",
        "Francine",
        "Francisca",
        "Fulgencia",
        "Fulva",
        "Fulvia",
        "Fulviana",
        "Gabria",
        "Gabriela",
        "Gabriele",
        "Gaia",
        "Galena",
        "Gardenia",
        "Gasparina",
        "Gaudia",
        "Gaudiana",
        "Genara",
        "Generosa",
        "Geralda",
        "Geraldina",
        "Germana",
        "Germania",
        "Germanica",
        "Gilberta",
        "Gilbertina",
        "Giovana",
        "Glafira",
        "Glenda",
        "Gliceria",
        "Glicerina",
        "Gloria",
        "Godofreda",
        "Goncala",
        "Goncalva",
        "Graca",
        "Graciana",
        "Graciane",
        "Graciela",
        "Graciele",
        "Gracilia",
        "Graciliana",
        "Gracinda",
        "Graciosa",
        "Graziela",
        "Graziele",
        "Gregoria",
        "Gregoriana",
        "Guilherma",
        "Guilhermina",
        "Gustava",
        "Gustavina",
        "Habacuque",
        "Harolda",
        "Helena",
        "Helenita",
        "Helia",
        "Heliodora",
        "Heliogabala",
        "Hendriga",
        "Henrica",
        "Henriqueta",
        "Heraclia",
        "Heraclita",
        "Herculana",
        "Hermana",
        "Hernanda",
        "Herodia",
        "Herodiana",
        "Hilaria",
        "Honesta",
        "Honestina",
        "Honorata",
        "Honoria",
        "Honorina",
        "Horacia",
        "Horaciana",
        "Huga",
        "Humberta",
        "Iaga",
        "Iluminata",
        "Imaculada",
        "Inacia",
        "Inaciana",
        "Ines",
        "Inesita",
        "Ingride",
        "Inocencia",
        "Iolanda",
        "Iracema",
        "Irapua",
        "Irene",
        "Iris",
        "Isamar",
        "Itaca",
        "Itaco",
        "Itala",
        "Italia",
        "Italiana",
        "Iva",
        "Ivana",
        "Ivanilda",
        "Ivanilde",
        "Jaci",
        "Jacinta",
        "Jacintina",
        "Jacoma",
        "Jaira",
        "Jamile",
        "Jana",
        "Janaina",
        "Jandira",
        "Jania",
        "Janina",
        "Januaria",
        "Jaqueline",
        "Jea",
        "Jeane",
        "Jessica",
        "Jesuina",
        "Joana",
        "Joanina",
        "Joaquina",
        "Josefa",
        "Josefina",
        "Jovina",
        "Joviniana",
        "Jucara",
        "Julia",
        "Juliana",
        "Juliane",
        "Julieta",
        "Julina",
        "Junia",
        "Juniana",
        "Junina",
        "Juno",
        "Jurema",
        "Justa",
        "Justina",
        "Justiniana",
        "Juvencia",
        "Juvenil",
        "Juvenilia",
        "Juventina",
        "Lauda",
        "Laudela",
        "Laudelina",
        "Laura",
        "Laurencia",
        "Laurentina",
        "Laurita",
        "Lavinia",
        "Leandra",
        "Leandrina",
        "Leda",
        "Ledica",
        "Ledice",
        "Ledo",
        "Leona",
        "Leonarda",
        "Leonardina",
        "Leoncia",
        "Leone",
        "Leonina",
        "Leopolda",
        "Leopoldina",
        "Lepida",
        "Leticia",
        "Leticiana",
        "Libera",
        "Liberal",
        "Liberalina",
        "Liberata",
        "Liberdade",
        "Liberta",
        "Libertaria",
        "Libertina",
        "Licinia",
        "Lilia",
        "Liliana",
        "Liliane",
        "Linda",
        "Lindalva",
        "Lindolfa",
        "Liria",
        "Liriel",
        "Lisandra",
        "Lisandrina",
        "Livia",
        "Liviana",
        "Livina",
        "Lourenca",
        "Lucelia",
        "Lucia",
        "Luciana",
        "Luciane",
        "Luciene",
        "Lucila",
        "Lucilene",
        "Lucilia",
        "Luciliana",
        "Lucula",
        "Luculo",
        "Ludovica",
        "Luisa",
        "Lupercia",
        "Luz",
        "Luzia",
        "Macae",
        "Madalena",
        "Mafalda",
        "Magali",
        "Magna",
        "Magnolia",
        "Maira",
        "Maisa",
        "Malva",
        "Malvina",
        "Manuela",
        "Manuelina",
        "Manuelita",
        "Mara",
        "Marca",
        "Marcal",
        "Marcela",
        "Marcelina",
        "Marcia",
        "Marciana",
        "Marcilia",
        "Marciliana",
        "Margarete",
        "Margarida",
        "Maria",
        "Marialva",
        "Mariana",
        "Mariane",
        "Marilda",
        "Marilena",
        "Marilene",
        "Marilia",
        "Marina",
        "Marisa",
        "Maristela",
        "Maro",
        "Marta",
        "Marte",
        "Martina",
        "Martinha",
        "Martiniana",
        "Marto",
        "Matias",
        "Maxima",
        "Maximilia",
        "Maximiliana",
        "Mecenas",
        "Meire",
        "Melania",
        "Melanina",
        "Menda",
        "Mentora",
        "Mercedes",
        "Micaela",
        "Michela",
        "Michele",
        "Miguelina",
        "Milena",
        "Miquelangela",
        "Miquelina",
        "Miranda",
        "Miria",
        "Modesta",
        "Modestina",
        "Moncaide",
        "Monica",
        "Morgana",
        "Mucia",
        "Muciana",
        "Murila",
        "Nailse",
        "Nanci",
        "Naomi",
        "Narcisa",
        "Natal",
        "Natalia",
        "Natalicia",
        "Natalina",
        "Nazare",
        "Nazarena",
        "Nice",
        "Nicole",
        "Nila",
        "Nilza",
        "Nivea",
        "Noeli",
        "Noelia",
        "Noemi",
        "Noemia",
        "Norma",
        "Noronha",
        "Novacia",
        "Novaciana",
        "Novata",
        "Nubia",
        "Numeria",
        "Numeriana",
        "Ofelia",
        "Olava",
        "Olimpa",
        "Olimpia",
        "Olimpiana",
        "Oliva",
        "Olivia",
        "Onesima",
        "Orlanda",
        "Orlandina",
        "Osmarina",
        "Osvalda",
        "Osvaldina",
        "Otavia",
        "Otaviana",
        "Pabla",
        "Paia",
        "Paloma",
        "Palomina",
        "Pamela",
        "Pancracia",
        "Paola",
        "Pascalina",
        "Pascoalina",
        "Patricia",
        "Paula",
        "Paulina",
        "Pedra",
        "Pedrina",
        "Pelagia",
        "Pelaia",
        "Peregrina",
        "Perla",
        "Perola",
        "Perpetua",
        "Perseveranda",
        "Persia",
        "Persiana",
        "Pietra",
        "Placida",
        "Placidina",
        "Plinia",
        "Postuma",
        "Postumia",
        "Pretextata",
        "Prisca",
        "Prisciana",
        "Priscila",
        "Prisciliana",
        "Prudencia",
        "Prudenciana",
        "Publia",
        "Publiana",
        "Querubina",
        "Quinta",
        "Quintilia",
        "Quintiliana",
        "Quintina",
        "Quiteria",
        "Raimunda",
        "Ramira",
        "Ramona",
        "Raquel",
        "Regia",
        "Regiana",
        "Regiane",
        "Regina",
        "Reginalda",
        "Reinalda",
        "Renata",
        "Ricarda",
        "Ricardina",
        "Rita",
        "Rodolfa",
        "Rodriga",
        "Rolanda",
        "Romana",
        "Romaria",
        "Ronalda",
        "Rosa",
        "Rosalia",
        "Rosalina",
        "Rosalinda",
        "Rosalva",
        "Rosamunda",
        "Rosana",
        "Rosane",
        "Rosangela",
        "Rosaria",
        "Rosaura",
        "Roseli",
        "Rosemeire",
        "Rosenda",
        "Rosina",
        "Rute",
        "Sabata",
        "Sabatina",
        "Sabelia",
        "Sabrina",
        "Salete",
        "Salustia",
        "Salustiana",
        "Salva",
        "Salvadora",
        "Salvia",
        "Salviana",
        "Salvina",
        "Samanta",
        "Samara",
        "Samaritana",
        "Sancha",
        "Sandra",
        "Sandrina",
        "Santa",
        "Santiaga",
        "Santina",
        "Sara",
        "Sarita",
        "Satira",
        "Saturna",
        "Saturnina",
        "Saulina",
        "Savia",
        "Saviana",
        "Sebastiana",
        "Sempronia",
        "Serafina",
        "Serena",
        "Sergia",
        "Sergiana",
        "Sergiane",
        "Severa",
        "Severiana",
        "Severina",
        "Silvana",
        "Silveria",
        "Silverina",
        "Silvestrina",
        "Silvia",
        "Silviana",
        "Silvina",
        "Simara",
        "Simona",
        "Simone",
        "Sinfronia",
        "Sinval",
        "Sista",
        "Sofonias",
        "Solana",
        "Solange",
        "Suelen",
        "Sueli",
        "Susana",
        "Susane",
        "Suzana",
        "Suzane",
        "Talia",
        "Talita",
        "Tatiana",
        "Tatiane",
        "Tela",
        "Teobalda",
        "Teodora",
        "Teofrasta",
        "Tiaga",
        "Tomasia",
        "Tranquila",
        "Tranquilina",
        "Tulia",
        "Tuliana",
        "Ubalda",
        "Ubaldina",
        "Ulpia",
        "Ulpiana",
        "Urana",
        "Urania",
        "Ursula",
        "Ursulina",
        "Valda",
        "Valdete",
        "Valdirene",
        "Valencia",
        "Valenciana",
        "Valentina",
        "Valentiniana",
        "Valeria",
        "Valeriana",
        "Valesca",
        "Valquiria",
        "Vanda",
        "Vanessa",
        "Vania",
        "Vanusa",
        "Vasca",
        "Venancia",
        "Veneranda",
        "Venina",
        "Vera",
        "Veridia",
        "Veridiana",
        "Verissima",
        "Vermuda",
        "Veronica",
        "Vespasia",
        "Vespasiana",
        "Vicencia",
        "Vicentina",
        "Virtuosa",
        "Vitoria",
        "Vitoriana",
        "Xista",
        "Yasmin",
        "Zaira",
        "Zelia",
        "Zenaida",
        "Zenaide",
        "Zulmira", ]

    sobrenomes = [
        "Abreu",
        "Adaes",
        "Adorno",
        "Aguiar",
        "Albuquerque",
        "Alcantara",
        "Aleluia",
        "Alencar",
        "Almeida",
        "Altamirano",
        "Alvarenga",
        "Alvares",
        "Alves",
        "Alvim",
        "Amaral",
        "Amigo",
        "Amor",
        "Amorim",
        "Anchieta",
        "Andrada",
        "Andrade",
        "Anes",
        "Anjos",
        "Antunes",
        "Anunciacao",
        "Aragao",
        "Araujo",
        "Arruda",
        "Ascensao",
        "Assis",
        "Azeredo",
        "Azevedo",
        "Bandeira",
        "Barbosa",
        "Barros",
        "Barroso",
        "Bastos",
        "Batista",
        "Bermudes",
        "Bernades",
        "Bernardes",
        "Bicalho",
        "Bispo",
        "Bocaiuva",
        "Borba",
        "Borges",
        "Borsoi",
        "Botelho",
        "Braga",
        "Braganca",
        "Brandao",
        "Brasil",
        "Brasiliense",
        "Bueno",
        "Cabral",
        "Cafe",
        "Camacho",
        "Camargo",
        "Caminha",
        "Camoes",
        "Cardoso",
        "Carmo",
        "Carnaval",
        "Carneiro",
        "Carvalhal",
        "Carvalho",
        "Carvalhosa",
        "Castilho",
        "Castro",
        "Cerejeira",
        "Chaves",
        "Coelho",
        "Coentrao",
        "Coimbra",
        "Constante",
        "Cordeiro",
        "Costa",
        "Cotrim",
        "Coutinho",
        "Couto",
        "Cruz",
        "Cunha",
        "Curado",
        "Dambros",
        "Dias",
        "Diegues",
        "Dorneles",
        "Duarte",
        "Eca",
        "Encarnacao",
        "Esteves",
        "Evangelista",
        "Exaltacao",
        "Fagundes",
        "Faleiros",
        "Falopio",
        "Falqueto",
        "Faria",
        "Farias",
        "Faro",
        "Fernandes",
        "Ferrao",
        "Ferraz",
        "Ferreira",
        "Ferrolho",
        "Figo",
        "Figueira",
        "Figueiredo",
        "Figueiroa",
        "Fioravante",
        "Fonseca",
        "Fontes",
        "Fortaleza",
        "Franca",
        "Freire",
        "Freitas",
        "Frota",
        "Furquim",
        "Furtado",
        "Galvao",
        "Gama",
        "Garrastazu",
        "Gato",
        "Gomes",
        "Goncales",
        "Goncalves",
        "Gonzaga",
        "Gouveia",
        "Guimaraes",
        "Gusmao",
        "Henriques",
        "Hernandes",
        "Holanda",
        "Homem",
        "Hora",
        "Hungria",
        "Jardim",
        "Junqueira",
        "Lacerda",
        "Lange",
        "Leitao",
        "Leite",
        "Leme",
        "Lins",
        "Locatelli",
        "Lopes",
        "Luz",
        "Macedo",
        "Machado",
        "Madureira",
        "Maduro",
        "Magalhaes",
        "Mairinque",
        "Malafaia",
        "Malta",
        "Mariz",
        "Marques",
        "Martins",
        "Massa",
        "Matos",
        "Medici",
        "Meireles",
        "Mello",
        "Melo",
        "Mendes",
        "Mendonca",
        "Menino",
        "Mesquita",
        "Miranda",
        "Monteiro",
        "Moraes",
        "Morais",
        "Morato",
        "Moreira",
        "Moro",
        "Muniz",
        "Namorado",
        "Nantes",
        "Nascimento",
        "Navarro",
        "Naves",
        "Negreiros",
        "Negrete",
        "Neves",
        "Nobrega",
        "Nogueira",
        "Noronha",
        "Nunes",
        "Oliva",
        "Oliveira",
        "Outeiro",
        "Pacheco",
        "Padrao",
        "Paes",
        "Pais",
        "Paiva",
        "Paixao",
        "Papanicolau",
        "Parga",
        "Pascal",
        "Pascoal",
        "Pasquim",
        "Patriota",
        "Pecanha",
        "Pedrosa",
        "Pedroso",
        "Peixoto",
        "Pensamento",
        "Penteado",
        "Pereira",
        "Peres",
        "Pessoa",
        "Pestana",
        "Pimenta",
        "Pimentel",
        "Pinheiro",
        "Pinto",
        "Pires",
        "Poeta",
        "Policarpo",
        "Porto",
        "Portugal",
        "Prado",
        "Prudente",
        "Quaresma",
        "Queiros",
        "Queiroz",
        "Ramalhete",
        "Ramalho",
        "Ramires",
        "Ramos",
        "Rangel",
        "Reis",
        "Resende",
        "Ribeiro",
        "Rios",
        "Rodrigues",
        "Roma",
        "Romao",
        "Sa",
        "Sacramento",
        "Sampaio",
        "Sampaulo",
        "Sampedro",
        "Sanches",
        "Santacruz",
        "Santana",
        "Santander",
        "Santarrosa",
        "Santiago",
        "Santos",
        "Saragoca",
        "Saraiva",
        "Saramago",
        "Seixas",
        "Serra",
        "Serrano",
        "Silva",
        "Silveira",
        "Simoes",
        "Siqueira",
        "Soares",
        "Soeiro",
        "Sousa",
        "Souza",
        "Tavares",
        "Teixeira",
        "Teles",
        "Torquato",
        "Trindade",
        "Uchoa",
        "Uribe",
        "Valadares",
        "Valenca",
        "Valente",
        "Varela",
        "Vasconcelos",
        "Vasques",
        "Vaz",
        "Veiga",
        "Velasques",
        "Veloso",
        "Viana",
        "Vieira",
        "Vilela",
        "Vilhena",
        "Xavier",
        "Zampol"
    ]
    # sobrenomes
    l_sobrenomes = sobrenomes  # todos
    if quantidade < len(sobrenomes) // 40:
        l_sobrenomes = random.sample(sobrenomes, quantidade * 40)

    # femininos
    qtd = len(prenomes_femininos) // 5
    l_nomes_fem = random.sample(prenomes_femininos, qtd)
    l_primeiro_nome_fem = l_nomes_fem[:qtd // 2]
    l_nome_meio_fem = l_nomes_fem[qtd // 2:]
    l_nomes_femininos = random.sample(
        [" ".join([p, s]) for p in l_primeiro_nome_fem
         for s in l_sobrenomes], quantidade * 5) + random.sample(
        [" ".join([p, m, s])
         for p in l_primeiro_nome_fem for m in l_nome_meio_fem
         for s in l_sobrenomes], quantidade * 5)
    # print(l_nomes_femininos)

    # masculinos
    qtd = len(prenomes_masculinos) // 5
    l_nomes_masc = random.sample(prenomes_masculinos, qtd)
    l_primeiro_nome_masc = l_nomes_masc[:qtd // 2]
    l_nome_meio_masc = l_nomes_masc[qtd // 2:]
    l_nomes_masculinos = random.sample(
        [" ".join([p, s]) for p in l_primeiro_nome_masc
         for s in l_sobrenomes], quantidade * 5) + random.sample(
        [" ".join([p, m, s])
         for p in l_primeiro_nome_masc for m in l_nome_meio_masc
         for s in l_sobrenomes], quantidade * 5)

    return random.sample(l_nomes_femininos + l_nomes_masculinos, quantidade)


def lista_telefones(quantidade):
    lista = ["{}{} {}{}-{}".format(ddd1, ddd2, digito9, pref, num)
             for ddd1 in range(1, 10)
             for ddd2 in [1, 3, 5]
             for digito9 in [9] * 4 + [''] * 6
             for pref in random.sample(range(1111, 9999), quantidade * 2)
             for num in random.sample(range(1111, 9999), quantidade * 2)]
    return random.sample(lista, quantidade)


def lista_enderecos(quantidade):
    lista_tipo = 10 * ["Rua"] + 8 * ["Avenida"] + ["Travessa",
                                                   "Passeio", "Alameda", "Via"]
    lista_logradouros = lista_nomes(quantidade)
    return ["{} {}, {}".format(
        lista_tipo[random.randint(0, len(lista_tipo) - 1)],
        nome,
        random.randint(10, 3000))
        for nome in lista_logradouros]


def lista_estados(quantidade):
    lista_unidades = [
        ["AC", "Acre"],
        ["AL", "Alagoas"],
        ["AP", "Amapá"],
        ["AM", "Amazonas"],
        ["BA", "Bahia"],
        ["CE", "Ceará"],
        ["ES", "Espírito Santo"],
        ["GO", "Goiás"],
        ["MA", "Maranhão"],
        ["MT", "Mato Grosso"],
        ["MS", "Mato Grosso do Sul"],
        ["MG", "Minas Gerais"],
        ["PA", "Pará"],
        ["PB", "Paraíba"],
        ["PR", "Paraná"],
        ["PE", "Pernambuco"],
        ["PI", "Piauí"],
        ["RJ", "Rio de Janeiro"],
        ["RN", "Rio Grande do Norte"],
        ["RS", "Rio Grande do Sul"],
        ["RO", "Rondônia"],
        ["RR", "Roraima"],
        ["SC", "Santa Catarina"],
        ["SP", "São Paulo"],
        ["SE", "Sergipe"],
        ["TO", "Tocantins"],
        ["DF", "Distrito Federal"]
    ]
    return random.sample(lista_unidades, quantidade)
